In [204]:
#function for checking if it is the winning piece
#function to check valid row dropped
#function to find next open spot within a row
#function to create board


In [1]:
import numpy as np
import pygame
import sys
import math as m

pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
TOTALROWS=6
TOTALCOLUMNS=7

In [3]:
def is_valid(board):
    global column #using global because this function changes the column variable. Without global, the variable will only change locally but global columb variable wont change
    if board[0,column]==0:
        return True
    #else:   #No need this because its visiual, without the visual then need this
        #while board[0,column] !=0:
            #column=int(input('Your selection is invalid, please make a VALID selection (0-6):',))
            #print(column)
            #if board[0,column]==0:
                #return True
            
    
def next_open_row(column,board):
    for row in range((TOTALROWS)-1,-1,-1):
        if board[row,column]==0:
            return row

def winning_move(board,move):
    global gameover
    for c in range(TOTALCOLUMNS-3): #checking horizontally
        for r in range(TOTALROWS):
            if turn ==1:
                if board[r][c]==1 and board[r][c+1]==1 and board[r][c+2]==1 and board[r][c+3]==1:
                    gameover=True

            else:
                if board[r][c]==2 and board[r][c+1]==2 and board[r][c+2]==2 and board[r][c+3]==2:
                    gameover=True

    
    for r in range(TOTALROWS-3): #checking vertically
        for c in range(TOTALCOLUMNS):
            if turn ==1:
                if board[r][c]==1 and board[r+1][c]==1 and board[r+2][c]==1 and board[r+3][c]==1:
                    gameover=True

            else:
                if board[r][c]==2 and board[r+1][c]==2 and board[r+2][c]==2 and board[r+3][c]==2:
                    gameover=True

                    
    


    for c in range(TOTALCOLUMNS-3): #checking diagonal down
        for r in range(TOTALROWS-3):
            if turn ==1:
                if board[r][c]==1 and board[r+1][c+1]==1 and board[r+2][c+2]==1 and board[r+3][c+3]==1:
                    gameover=True

            else:
                if board[r][c]==2 and board[r+1][c+1]==2 and board[r+2][c+2]==2 and board[r+3][c+3]==2:
                    gameover=True

    
    for c in range(TOTALCOLUMNS-3): #checking diagonal up
        for r in range(TOTALROWS-1,TOTALROWS-4,-1):
            if turn ==1:
                if board[r][c]==1 and board[r-1][c+1]==1 and board[r-2][c+2]==1 and board[r-3][c+3]==1:
                    gameover=True

            else:
                if board[r][c]==2 and board[r-1][c+1]==2 and board[r-2][c+2]==2 and board[r-3][c+3]==2:
                    gameover=True

                  
    
    

In [4]:
board = np.zeros((6,7))
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
BLUE=(0,0,200)
BLACK=(0,0,0)
RED=(200,0,0)
YELLOW=(200,200,0)



In [6]:
def draw_board(board):
    for c in range(TOTALCOLUMNS):
        for r in range(TOTALROWS):
            pygame.draw.rect(screen,BLUE,(c*SQUARESIZE,r*SQUARESIZE+SQUARESIZE,SQUARESIZE,SQUARESIZE)) #(where,color,position(x,y),width,height)
            if board[r,c]==0:
                pygame.draw.circle(screen,BLACK,(int(c*SQUARESIZE+SQUARESIZE/2),int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)),RADIUS)
            elif board[r,c]==1:
                pygame.draw.circle(screen,RED,(int(c*SQUARESIZE+SQUARESIZE/2),int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)),RADIUS) #(where,color,x axis position, y axis position)
            else:
                pygame.draw.circle(screen,YELLOW,(int(c*SQUARESIZE+SQUARESIZE/2),int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)),RADIUS)
            pygame.display.update()    
                
                
                

In [7]:
pygame.init() #initiating game
SQUARESIZE =100 #initiatin squre size
RADIUS=int(SQUARESIZE/2)-5
width=TOTALCOLUMNS*SQUARESIZE #width of total screen
height=(TOTALROWS+1)*SQUARESIZE #height of total screen
size=(width,height) #size of screen
screen=pygame.display.set_mode(size) #initiate screen
draw_board(board) #draw the board
pygame.display.update()
myfont=pygame.font.SysFont('monospace',75) #initiate font

gameover=False
turn=1
while gameover==False:
    for event in pygame.event.get(): #supposedly do this for window not to crash
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()
            sys.exit()
        if event.type == pygame.MOUSEMOTION: #making red and yellow dot at the top of the game before dropping
            pygame.draw.rect(screen,BLACK,(0,0,width,SQUARESIZE)) #start point, witdth, height
            posx=event.pos[0]
            if turn==1:
                pygame.draw.circle(screen,RED,(posx,int(SQUARESIZE/2)),RADIUS) #draw red circle
            if turn==2:
                pygame.draw.circle(screen,YELLOW,(posx,int(SQUARESIZE/2)),RADIUS) #draw yellow circle
            pygame.display.update()
        if event.type == pygame.MOUSEBUTTONDOWN: #when clicking
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE)) #draw black after clicking so that when when user wins, the dot leaves and 'Player winner' banner shows up
            if turn==1:
                posx=event.pos[0] #find x position
                column=int(m.floor(posx/SQUARESIZE)) #convert to column
        #column=int(input('Player 1: Please make selection (0-6):',))
        #print('column is',column)
        
    
                if is_valid(board):
                    print(is_valid(board))
                    row=next_open_row(column,board)
                    print('row is',row)
                    print('column is',column)
                    move=[row,column]
                    print(move)
                    print(move[1])
                    board[row,column]=1
                    print(board)
                    winning_move(board,move)
                    if gameover==True:
                        label=myfont.render("Player 1 wins!!",1,RED)
                        screen.blit(label,(40,10))
                        

                        
        
            if (turn == 2 and gameover==False):
                posx=event.pos[0] #get the position of the click
                column=int(m.floor(posx/SQUARESIZE)) #convert the position into a column
                if is_valid(board):
                    print(is_valid(board))
                    row=next_open_row(column,board)
                    print('row is',row)
                    print('column is',column)
                    move=[row,column]
                    board[row,column]=2
                    print(board)
                    winning_move(board,move)
                    if gameover==True:
                        label=myfont.render("Player 1 wins!!",1,YELLOW)
                        screen.blit(label,(40,10))
                        

            draw_board(board)
            if turn==1:
                turn=2
            elif turn==2:
                turn=1
        
        
        
        
    

True
row is 5
column is 1
[5, 1]
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
True
row is 5
column is 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
True
row is 4
column is 1
[4, 1]
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
True
row is 4
column is 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
True
row is 3
column is 1
[3, 1]
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
True
row is 3
column is 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 

In [1]:
import numpy as np
import pygame
import sys
import math

BLUE = (0,0,255)
BLACK = (0,0,0)
RED = (255,0,0)
YELLOW = (255,255,0)

ROW_COUNT = 6
COLUMN_COUNT = 7

def create_board():
	board = np.zeros((ROW_COUNT,COLUMN_COUNT))
	return board

def drop_piece(board, row, col, piece):
	board[row][col] = piece

def is_valid_location(board, col):
	return board[ROW_COUNT-1][col] == 0

def get_next_open_row(board, col):
	for r in range(ROW_COUNT):
		if board[r][col] == 0:
			return r

def print_board(board):
	print(np.flip(board, 0))

def winning_move(board, piece):
	# Check horizontal locations for win
	for c in range(COLUMN_COUNT-3):
		for r in range(ROW_COUNT):
			if board[r][c] == piece and board[r][c+1] == piece and board[r][c+2] == piece and board[r][c+3] == piece:
				return True

	# Check vertical locations for win
	for c in range(COLUMN_COUNT):
		for r in range(ROW_COUNT-3):
			if board[r][c] == piece and board[r+1][c] == piece and board[r+2][c] == piece and board[r+3][c] == piece:
				return True

	# Check positively sloped diaganols
	for c in range(COLUMN_COUNT-3):
		for r in range(ROW_COUNT-3):
			if board[r][c] == piece and board[r+1][c+1] == piece and board[r+2][c+2] == piece and board[r+3][c+3] == piece:
				return True

	# Check negatively sloped diaganols
	for c in range(COLUMN_COUNT-3):
		for r in range(3, ROW_COUNT):
			if board[r][c] == piece and board[r-1][c+1] == piece and board[r-2][c+2] == piece and board[r-3][c+3] == piece:
				return True

def draw_board(board):
	for c in range(COLUMN_COUNT):
		for r in range(ROW_COUNT):
			pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE+SQUARESIZE, SQUARESIZE, SQUARESIZE))
			pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)
	
	for c in range(COLUMN_COUNT):
		for r in range(ROW_COUNT):		
			if board[r][c] == 1:
				pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
			elif board[r][c] == 2: 
				pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
	pygame.display.update()


board = create_board()
print_board(board)
game_over = False
turn = 0

pygame.init()

SQUARESIZE = 100

width = COLUMN_COUNT * SQUARESIZE
height = (ROW_COUNT+1) * SQUARESIZE

size = (width, height)

RADIUS = int(SQUARESIZE/2 - 5)

screen = pygame.display.set_mode(size)
draw_board(board)
pygame.display.update()

myfont = pygame.font.SysFont("monospace", 75)

while not game_over:

	for event in pygame.event.get():
		if event.type == pygame.QUIT:
			sys.exit()

		if event.type == pygame.MOUSEMOTION:
			pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
			posx = event.pos[0]
			if turn == 0:
				pygame.draw.circle(screen, RED, (posx, int(SQUARESIZE/2)), RADIUS)
			else: 
				pygame.draw.circle(screen, YELLOW, (posx, int(SQUARESIZE/2)), RADIUS)
		pygame.display.update()

		if event.type == pygame.MOUSEBUTTONDOWN:
			pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
			#print(event.pos)
			# Ask for Player 1 Input
			if turn == 0:
				posx = event.pos[0]
				col = int(math.floor(posx/SQUARESIZE))

				if is_valid_location(board, col):
					row = get_next_open_row(board, col)
					drop_piece(board, row, col, 1)

					if winning_move(board, 1):
						label = myfont.render("Player 1 wins!!", 1, RED)
						screen.blit(label, (40,10))
						game_over = True


			# # Ask for Player 2 Input
			else:				
				posx = event.pos[0]
				col = int(math.floor(posx/SQUARESIZE))

				if is_valid_location(board, col):
					row = get_next_open_row(board, col)
					drop_piece(board, row, col, 2)

					if winning_move(board, 2):
						label = myfont.render("Player 2 wins!!", 1, YELLOW)
						screen.blit(label, (40,10))
						game_over = True

			print_board(board)
			draw_board(board)

			turn += 1
			turn = turn % 2

			if game_over:
				pygame.time.wait(3000)

pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]]


SystemExit: 

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
